# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec0b3eef9da3ec1d56cf7cbd2183387427538cf7dcc6dcc7a36c3f503d573c23632d15b5666a1736c532f55e028e215750ec0d6dbabc39f05f64eb836c9d267b

test:
  secret_key_base: 632a020d0cb9629d52c7c059a706ae770f73e2689f746bc323bbd5a25cdfe894d3140f8b83063d6ffce918a813a790c3341664b8effed57bf62379fe8c375694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
